### PR TITLE
[blocked on github actions stability] Add github actions testing

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

**Comment by spacejam** [comment]
It seems as though github actions are encountering frequent SSL errors when interacting with crates.io

Probably not quite time to make this live yet

**Comment by spacejam** [comment]
https://github.com/actions/cache

**Comment by tbillington** [comment]
Hi! I saw this project a couple days ago, I'm not sure if it will be of any help but might be handy as a reference https://github.com/XAMPPRocky/mean-bean-ci-template.

**Comment by spacejam** [comment]
superceded by #985

**Pull request closed without merging**
