### PR TITLE
don't scan through empty pagetable entries on Drop because it's assumed to be dense

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

**Comment by spacejam** [comment]
@mxinden and this should get rid of almost all of the pagetable destruction latency

**Comment by spacejam** [comment]
There are some other areas that could still be optimized but it's sooo much better than before

[flamegraph.svg.zip](https://github.com/spacejam/sled/files/3428911/flamegraph.svg.zip)

**Comment by Kerollmops** [comment]
Do you have a before after svg? :)

**Comment by spacejam** [comment]
@Kerollmops unfortunately I deleted them already, but the difference is really clear when just starting and dropping a non-temporary database with a unique name 5000 times

**Pull request merged**
