### PR TITLE
Persisted Config

### PR DESCRIPTION
**Pull request by sitano**
ref: https://github.com/spacejam/sled/issues/679

### CODE REVIEW

**Comment by spacejam** [comment]
One issue that makes this a bit trickier, which I just remembered, is that there's a bit of a chicken and the egg problem here, where if the wrong config is used, it will never get to the step where it can read the last one, and it might just interpret the database file as garbage and delete it all. That's probably not a good outcome. I'm starting to think that we might want to keep the separate config file so we can detect changes before they accidentally delete anything.

It seems like most of this PR is cleaning other things up though, so I'm happy to merge in that part, but I think this config issue might actually cause data loss :/ 

Apologies for only realizing this after seeing the code

**Comment by sitano** [comment]
:lol: how I missed it)

**Comment by sitano** [comment]
@spacejam is that right that currently the only things that affect page compatability is the use of compression and db version? we could e.g. treat those system pages in a special way, don't compress them ever, or store and calculate a checksum in config not to lost a data. The checksum in config will solve the problem of invalid incoming configuration. What do you think?

**Comment by spacejam** [comment]
I think the separate config file should be:
crc32 | u8 major LE | u8 minor LE | u8 compression bool 0 or 1 

even though we don't need a crc32 for 3 bytes of data, we're already using crc32 in a bunch of other places and it's better not to bring in any other dependencies or complexity. Over time we can add more fields in a grow-only manner.

write temp then mv to avoid tears

**Comment by sitano** [comment]
Not sure we are talking about the same. I meant that we could use checksums for Persistent Config stored in the page to ensure that we read it right even with different incoming configuration from the client.

**Pull request closed without merging**
