### PR TITLE
fix destructor deadlock from issue #1152

### PR DESCRIPTION
**Pull request by soro**
This should fix the deadlock from spacejam/sled#1152

https://github.com/spacejam/sled/issues/1152#issuecomment-686390978

### CODE REVIEW

**Comment by spacejam** [comment]
LGTM, thanks!

**Comment by spacejam** [comment]
hmm, when merged in with the tyler_subscriber_send_lock branch with the test for this, it still locks up sometimes

**Comment by spacejam** [comment]
similar stacktraces, with a writing thread blocked on the `sender.send` call in subscriber.rs. Going to revert this for now because it doesn't seem to address the test that is locking up.

**Comment by soro** [comment]
Interesting. It definitely is a scenario that could currently lead to deadlock, so I think it needs to be added either way eventually. But that means there is something else as well. I will look into it some more.

**Pull request merged**
