### PR TITLE
Add OS agnostic crash tests

### PR DESCRIPTION
**Pull request by roignpar**
This is what I wrote so far for  #397.
I used the strategy described by @divergentdave.
Test names are also used as dir names to easily share them with child processes.
Haven't added the batches tests yet. Should I add them? They are currently ignored.
Renamed the old test file to have it around for reference. Will remove it once this is done.

### CODE REVIEW

**Comment by divergentdave** [comment]
The batch crash tests are currently ignored because they are known to fail, (because batches can get corrupted with two consecutive crashes) and fixing them is an open issue. I'd recommend adding parallel tests for them, and ignoring them in the new integration test file.

**Comment by roignpar** [comment]
@divergentdave I'm not sure what you mean by "parallel" tests.
Add them to the new test file, but don't run them in `main`?

**Comment by divergentdave** [comment]
Sorry, didn't think that through. I guess you can't use the #[ignore] attribute in a file that doesn't use the test runner. At any rate, consider writing the code for doing crash tests with batches, and then comment out the lines that invoke it. Once batches have been redesigned later on, we can un-comment the lines to enable the test.

**Comment by roignpar** [comment]
@divergentdave I added the batch tests (commented out).
I think these are the minimal changes needed in order to remove `libc` from the crash tests.
Is there anything else that should be changed?

**Comment by spacejam** [comment]
Great work, @roignpar :] I'm excited to learn about how badly various operating systems start breaking due to poor fsync assumptions now xD 

I just fixed some merge conflicts caused by completely removing runtime snapshotting, which I did not trust very much.

**Comment by roignpar** [comment]
@spacejam Thanks for fixing the merge conflicts.
I'm completely new to sled, but if you think I can help with other (easy-ish) issues, let me know!

**Pull request merged**
