### PR TITLE
pagecache: get rid of several unwraps

### PR DESCRIPTION
**Pull request by lucab**
This removes several unwrapping points, handling options via match
statements instead. It also bubbles up a few additional error cases.

### CODE REVIEW

**Comment by spacejam** [comment]
Thanks @lucab :D

**Comment by lucab** [comment]
:+1: 
There are still quite a few panics and unwraps, it would be nice if you could mark the ones you want to retain long-term (if any), and add TODOs for the spurious ones.
I don't have any specific usage for sled/pagecache at the moment, but this kind of cleanups are perfect for killing [idle times](https://xkcd.com/303/) in a useful way.

**Comment by spacejam** [comment]
Maybe at some point today I'll sweep through and change all fail-stop
worthy ones from unwrap to expect. Earlier in the project everything was
fail stop, but especially after the failpoint tests were added the goal is
to encapsulate all failures that can result from io issues.

**Comment by spacejam** [comment]
been going through a bunch of these, about 100 left still lol... but going through and being more thorough has already caught a few interesting bugs

**Pull request merged**
