### PR TITLE
Format, clippy suggestions

### PR DESCRIPTION
**Pull request by sigaloid**
Seems to pass tests

### CODE REVIEW

**Comment by spacejam** [comment]
Hello, could you please separate the clippy suggestions from the fmt suggestions? I don't want to needlessly merge formatting changes right now, as different people all have different rustfmt configs and this constantly seems to shift over time, but things that remove clippy warnings are generally OK to merge.

**Comment by sigaloid** [comment]
Reverted

**Comment by spacejam** [comment]
LGTM, thank you for cleaning up these small messy bits :)

**Comment by spacejam** [comment]
upon closer look, I think the LRU code might have a bug in it, but no need to fix it. The main reformats from your split out PR have been merged. Closing this because the remaining changes that don't change semantics in possibly broken ways are just a small change from assert_eq to assert, so I'll do this in a separate branch real quick to get it moving.

**Pull request closed without merging**
