### PR TITLE
fix some clippy warnings

### PR DESCRIPTION
**Pull request by ozgur11235813**
related to #393

### CODE REVIEW

**Comment by ozgur11235813** [comment]
@spacejam what do you think about "this argument is passed by value, but not consumed in the function body" warnings, can they be fixed. There are a lot of them.

**Comment by spacejam** [comment]
@ozgur11235813 thanks for cleaning this up! 

re: consumed warnings, please don't change the ones in the public functions in `tree.rs` as I'm going to optimize the cloning away at some point, and we will consume them then.

**Comment by ozgur11235813** [comment]
you can merge this I will continue another time

**Comment by spacejam** [comment]
:+1:

**Pull request merged**
